### ISSUE TITLE
I think it's working with SOD now. Try the 3.4.3.3 release.

### ISSUE THREAD

**Issue by rygarstrong** [GovtGeek/Outfitter#19]
I think it's working with SOD now. Try the 3.4.3.3 release.

_Originally posted by @GovtGeek in https://github.com/GovtGeek/Outfitter/issues/17#issuecomment-1984945776_

**Comment by rygarstrong** [comment]
firstly thank you so much. it has more features then i could ever need. question i remember outfitter having stances for warriors e.g in def stance sword and shield equipped. i can physically  click on the bar with the outfits i have no idea how to bind them but its not changing stances if that makes sense. so if i have a macro for cast taunt change stance i will taunt but my gear stays as if its in arms. u just need the 3 stance options added or perhaps its there somewhere ?

**Comment by GovtGeek** [comment]
I think there used to be some stance stuff for warriors, but I don't know what happened to it (I'm not the original creator). I know you can create custom scripts to get the same effect for now.

```
-- $EVENTS UNIT_AURA PLAYER_ENTERING_WORLD
-- $DESC Equips the outfit when you are in a stance with the specified name

if GetShapeshiftForm() == 2 then
equip = true
end
```

Use the above for your Defensive Stance outfit. You can get there by clicking the down arrow next to the outfit and selecting the Automation -> Script option. It may say "Script (None)".

If you're trying to get it into a macro, you can ignore the stuff above and use the command line option
`/outfitter wear Tanking` and replace Tanking with whatever you named your outfit. Don't forget you can't change gear in combat, except weapons. Unfortunately, the weapon swap was disabled in Outfitter because of some API changes by Blizzard, so Outfitter won't even change weapons right now.
